################################# Default configuration ###################
baseURL = "https://examplesite.com"
title = "Trofeo Pico Cueto"
theme = "pico-cueto-theme"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "the race"
url = "#the-race"
weight = 1

[[Languages.en.menu.main]]
name = "sign up"
url = "#signup"
weight = 2

[[Languages.en.menu.main]]
name = "profile"
url = "#profile"
weight = 4

[[Languages.en.menu.main]]
name = "getting there"
url = "#getting"
weight = 5

[[Languages.en.menu.main]]
name = "previously"
url = "#gallery"
weight = 6

[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 8


#[[Languages.en.menu.main]]
#name = "info"
#url = "#info"
#weight = 3

#[[Languages.en.menu.main]]
#name = "news"
#url = "#news"
#weight = 7


################### Spanish Navigation ########################
[[Languages.es.menu.main]]
name = "la carrera"
url = "#the-race"
weight = 1

[[Languages.es.menu.main]]
name = "inscríbete"
url = "#signup"
weight = 2

[[Languages.es.menu.main]]
name = "perfil"
url = "#profile"
weight = 4

[[Languages.es.menu.main]]
name = "cómo llegar"
url = "#getting"
weight = 5

[[Languages.es.menu.main]]
name = "contacto"
url = "#contact"
weight = 7

#[[Languages.es.menu.main]]
#name = "info"
#url = "#info"
#weight = 3

#[[Languages.es.menu.main]]
#name = "noticias"
#url = "#news"
#weight = 6


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Trofeo Pico Cueto, relay trail-cross in Asturias, Spain"
author = "PBest"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "EN"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2021 Designed by [Cristina Areces](https://areces.eu), based on the [Meghna Theme](https://github.com/themefisher/meghna-hugo)"

################################ Spanish Language ########################
[Languages.es]
languageName = "ES"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2
home = "Portada"
copyright = "Copyright &copy; 2021 Diseñado por [Cristina Areces](https://areces.eu), basado en [Meghna](https://github.com/themefisher/meghna-hugo)"
